### ISSUE TITLE
`idim` vs `odim` confusion

### ISSUE THREAD

**Issue by ericphanson** [ZKSI/QuantumInformation.jl#55] opened 2019-03-25 17:01 UTC
Consider
```julia
julia> x = rand(2,3)
2×3 Array{Float64,2}:
 0.114562  0.388229  0.205366
 0.724321  0.280265  0.917904

julia> size(x)
(2, 3)

julia> K = KrausOperators([x])
KrausOperators{Array{Float64,2}}
    dimensions: (2, 3)
    [0.114562 0.388229 0.205366; 0.724321 0.280265 0.917904]

julia> K.idim
2

julia> K.odim
3
```

This seems strange to me, because `x` maps 3-dimensional vectors to 2-dimensional, so the input dimension of `K` should be 3-dimensional. For example, this seems wrong:

```julia
julia> K(rand(HilbertSchmidtStates(K.idim)))
ERROR: DimensionMismatch("matrix A has dimensions (2,3), matrix B has dimensions (2,2)")
```

Note
```julia
julia> K(rand(HilbertSchmidtStates(K.odim)))
2×2 Array{Complex{Float64},2}:
 0.0945641+4.23488e-18im  0.165292-0.0355746im  
  0.165292+0.0355746im    0.399333+2.45039e-17im
```
works, which seems strange.

`SuperOperators` have the same thing, where in <https://github.com/ZKSI/QuantumInformation.jl/blob/f0eb3d477fbd6984896edb55bee3de4eb583b22c/src/channels.jl#L58>, the input dimension is defined as the number of rows instead of the number of columns.

This came up for me because I construct a `DynamicalMatrix` from a `48x48` matrix which corresponds to a quantum channel from a 2 dimensional space to a 24 dimensional space. Then I convert it to a superoperator, `S`. Now, `S` has the correct values for `idim` and `odim` (2 and 24, respectively), but it's matrix representation has size `4x576` which seems backwards. Then when I try to act on a density matrix on an `idim` (=2) dimensional space, I get `DimensionMismatch` errors.

**Comment by pgawron** [comment] 2019-03-25 20:44
@ericphanson Good catch. Fixing this error causes a cascade of other errors. I'll have to investigate it.

**Comment by pgawron** [comment] 2019-03-25 22:16
@ericphanson The bug should be fixed in [branch pg/dimfix](https://github.com/ZKSI/QuantumInformation.jl/tree/pg/dimfix). Can you test this branch with your code and confirm that everything works as intended?

**Comment by ericphanson** [comment] 2019-03-25 23:59
Thanks for the quick fix! It seems like a lot of the dimension problems are fixed. I'm not sure if this is related or not, but in trying my code again, it seems like there might be something off with the tensor product of channels. Perhaps it's related to some kind of dimension mismatch. I'll include the full code I tried, because perhaps some of it is useful to copy into the tests (I consent to contribute it).

```julia
julia> using QuantumInformation, Test

julia> d_in = 2
2

julia> d_out = 24
24

julia> r = rand(HilbertSchmidtStates(d_out*d_in));

julia> J = DynamicalMatrix(r, d_in, d_out)
DynamicalMatrix{Array{Complex{Float64},2}}
    dimensions: (2, 24)
    Complex{Float64}[0.0180149+0.0im 0.0012049-0.00229732im … -0.00334511+0.00191591im -0.00252597-0.00528411im; 0.0012049+0.00229732im 0.0184454+0.0im … -0.00262492-0.0018415im -3.30124e-5+0.00113009im; … ; -0.00334511-0.00191591im -0.00262492+0.0018415im … 0.012501+0.0im 0.00091462+0.00118778im; -0.00252597+0.00528411im -3.30124e-5-0.00113009im … 0.00091462-0.00118778im 0.0265474+0.0im]

julia> @test J.idim == d_in
Test Passed

julia> @test J.odim == d_out
Test Passed

julia> S = convert(SuperOperator{Matrix{ComplexF64}}, J)
SuperOperator{Array{Complex{Float64},2}}
    dimensions: (2, 24)
    Complex{Float64}[0.0180149+0.0im 0.0012049-0.00229732im 0.0012049+0.00229732im 0.0184454+0.0im; 0.00048739+0.000309335im -0.00233232-0.00081684im -0.00123661+0.00270702im -0.00272312-0.00250587im; … ; 0.00126314+0.00215912im 0.00362822+0.000577661im 0.000144086+0.000962157im -0.00491926-0.0028762im; 0.012501+0.0im 0.00091462+0.00118778im 0.00091462-0.00118778im 0.0265474+0.0im]

julia> @test S.idim == d_in
Test Passed

julia> @test S.odim == d_out
Test Passed

julia> @test size(S.matrix) == (d_out^2, d_in^2)
Test Passed

julia> d_aux = 4
4

julia> Id = IdentityChannel(d_aux)
IdentityChannel{Array{Complex{Float64},2}}
    dimensions: (4, 4)


julia> chan = Id ⊗ S;

julia> @test chan.idim == d_in * d_aux
Test Passed

julia> @test chan.odim == d_out * d_aux
Test Passed

julia> σ = rand(HilbertSchmidtStates(d_aux * d_in));

julia> σ_out = chan(σ);

julia> σ_out_1 = ptrace(σ_out, [d_aux, d_out], 2 );

julia> σ_1 = ptrace(σ, [d_aux, d_in], 2 );

julia> @test σ_out_1 ≈ σ_1
Test Failed at REPL[87]:1
  Expression: σ_out_1 ≈ σ_1
   Evaluated: Complex{Float64}[0.160206-8.13361e-20im 0.053731+0.0194236im 0.0109607-0.00631307im 0.0192012+0.0124276im; 0.053731-0.0194236im 0.132708+1.61237e-19im 0.0265943+0.0066241im -0.0247346-0.0302378im; 0.0109607+0.00631307im 0.0265943-0.0066241im 0.112301-2.8821e-21im -0.030899-0.0164399im; 0.0192012-0.0124276im -0.0247346+0.0302378im -0.030899+0.0164399im 0.0931489-2.03993e-20im] ≈ Complex{Float64}[0.322102+0.0im 0.108533+0.0404885im 0.021574-0.0137212im 0.0381982+0.0269961im; 0.108533-0.0404885im 0.266784+0.0im 0.0529056+0.014329im -0.0500201-0.0600329im; 0.021574+0.0137212im 0.0529056-0.014329im 0.222919+0.0im -0.0631573-0.0317623im; 0.0381982-0.0269961im -0.0500201+0.0600329im -0.0631573+0.0317623im 0.188196+0.0im]
ERROR: There was an error during testing

julia> using LinearAlgebra

julia> norm(σ_out_1 - σ_1)
0.28450033646277695
```

The problem is that if we apply a channel only on the second system, then trace it out, we should get the same result as not applying the channel at all and just tracing out the second system.  Please let me know if I've mixed something up.

**Comment by lpawela** [comment] 2019-03-26 12:40
@ericphanson what you say is true for seprable input states. When the input state is entangled on `d_aux`, `d_in`, then the state of the susbsytem `d_aux` might also change. Random states sampled from the HilbertSchmidt distribution are almost surely entangled.

**Comment by ericphanson** [comment] 2019-03-26 13:45
Ah, sorry, `S` is (almost surely) not trace preserving, and so acting on the second system does change the partial trace. And in my code, where `S` is indeed a trace-preserving map (coming from an SDP), I get the right action of `Id ⊗ S`. But my code doesn't go beyond what I wrote in the last comment in terms of use of `QuantumInformation.jl`, so I can't comment on the rest of the dimension changes now (but I'll certainly let you know if I find more issues later).

**Comment by pgawron** [comment] 2019-03-26 13:47
@ericphanson It is not a bug. Your `J` variable does not contain proper quantum channel (CP-TP map). Therefore `@test σ_out_1 ≈ σ_1` should fail.
```julia
julia> r = rand(HilbertSchmidtStates(d_out*d_in));

julia> J = DynamicalMatrix(r, d_in, d_out)
```
Look at the following fix to your code we've written with @lpawela 

```julia
using Revise, QuantumInformation, Test
using LinearAlgebra

function test_channel(J, d_in, d_out, d_aux)
    @test J.idim == d_in
    @test J.odim == d_out
    S = convert(SuperOperator{Matrix{ComplexF64}}, J)
    @test S.idim == d_in
    @test S.odim == d_out
    @test size(S.matrix) == (d_out^2, d_in^2)
    ρ = rand(HilbertSchmidtStates(d_in))
    @test J(ρ) ≈ S(ρ)

    Id = IdentityChannel(d_aux)
    chan = Id ⊗ S
    @test chan.idim == d_in * d_aux
    @test chan.odim == d_out * d_aux
    σ = rand(HilbertSchmidtStates(d_aux * d_in))
    σ_out = chan(σ)
    σ_out_1 = ptrace(σ_out, [d_aux, d_out], [2])
    σ_1 = ptrace(σ, [d_aux, d_in], [2] )
    @test σ_out_1/tr(σ_out_1) ≈ σ_1/tr(σ_1)
    @test σ_out_1 ≈ σ_1

    norm(σ_out_1 - σ_1)
end

d_in = 2
d_out = 24
d_aux = 4

J = rand(ChoiJamiolkowskiMatrices(d_in, d_out))
Jcm = DynamicalMatrix(J.matrix, d_in, d_out)

x = rand(HilbertSchmidtStates(d_in * d_out)) * d_in
y = Hermitian(ptrace(x, [d_out, d_in], [1]))
x_norm = (𝕀(d_out)⊗inv(sqrt(y))) * x * (𝕀(d_out)⊗inv(sqrt(y)))
J_new = DynamicalMatrix(x_norm, d_in, d_out)

iscptni(J_new, atol=0.000001)

test_channel(J, d_in, d_out, d_aux)
test_channel(Jcm, d_in, d_out, d_aux)
test_channel(J_new, d_in, d_out, d_aux)
```

**Comment by ericphanson** [comment] 2019-03-26 13:54
Okay, looks good! Thanks.

**Comment by pgawron** [comment] 2019-03-26 15:04
Not a bug. Closing issue.

**Comment by ericphanson** [comment] 2019-03-26 16:07
Just to be clear, the dimensions being wrong is a bug, correct? Will you merge [pg/dimfix](https://github.com/ZKSI/QuantumInformation.jl/tree/pg/dimfix)?

**Comment by pgawron** [comment] 2019-03-26 17:05
@ericphanson I got confused, sorry. Of course I want to merge pg/dimfix branch.

**Closed** 2019-03-29 10:46 UTC
Labels: bug
